AUTO_SHIFT_ENABLE = yes
OLED_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes

CONSOLE_ENABLE = no
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no	
MUSIC_ENABLE = no
RGBLIGHT_ENABLE = no